print (mtcars)
print(?mtcars)
cat("nalargest horsepowet value \n")
cat("=====================================\n")
cat(max(mtcars$hp),"\n")
cat("\nsmallest horsepower value\n")
cat("===================================\n")
cat(min(mtcars$hp),"\n")
cat("\n name of the car with largest hp\n")
cat ("=========================================\n")
cat(rownames(mtcars)[which.max(mtcars$hp)],"\n")
cat("\n average weight of a car\n")
cat("=======================================\n")
cat(mean(mtcars$wt),"\n")
cat ("\n middle point of car weight\n")
cat("=====================================\n")
cat(median(mtcars$wt),"\n")
cat ("\n mode value of car weight\n")
cat("=====================================\n")
cat(names(sort(table(mtcars$Wt),decreasing=TRUE))[1],"\n")
cat("\n quartile values\n")
cat("==================================\n")
print(quantile(mtcars$Wt))
