data <- read.csv("data.csv",header = TRUE)
summary_stats <- summary(data$Age)
print(paste("Summary statistices for Age:",summary_stats))
mean_age <- mean(data$Age)
print(paste("Mean Age:",mean_age))
max_age <-max(data$Age)
print(paste("Maximum Age:",max_age))
max_age <-max(data$Age)
print(paste("Maximum Age:",max_age))